const nodeColor = [
    'red',
    'red lighten-1',
    'red lighten-2',
    'pink',
    'pink lighten-1',
    'pink lighten-2',
    'purple',
    'purple lighten-1',
    'purple lighten-2',
    'deep-purple',
    'deep-purple lighten-1',
    'deep-purple lighten-2',
    'indigo',
    'indigo lighten-1',
    'indigo lighten-2',
    'blue',
    'blue lighten-1',
    'blue lighten-2',
    'cyan',
    'cyan lighten-1',
    'cyan lighten-2',
    'teal',
    'teal lighten-1',
    'teal lighten-2',
    'green',
    'green lighten-1',
    'green lighten-2',
    'lime',
    'lime lighten-1',
    'lime lighten-2',
    'yellow',
    'yellow lighten-1',
    'yellow lighten-2',
    'amber',
    'amber lighten-1',
    'amber lighten-2',
    'orange',
    'orange lighten-1',
    'orange lighten-2',
    'brown',
    'brown lighten-1',
    'brown lighten-2',
    'blue-grey',
    'blue-grey lighten-1',
    'blue-grey lighten-2',
];

export default nodeColor;
